"""initial version

Revision ID: f02202283a3c
Revises: 
Create Date: 2026-05-27 11:34:21.391620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f02202283a3c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_result_cache',
    sa.Column('cache_key', sa.String(length=64), nullable=False),
    sa.Column('module_name', sa.String(length=512), nullable=False),
    sa.Column('module_version', sa.Integer(), nullable=False),
    sa.Column('observable_type', sa.String(length=64), nullable=False),
    sa.Column('observable_value', sa.Text(), nullable=False),
    sa.Column('delta_zstd', mysql.LONGBLOB(), nullable=False),
    sa.Column('delta_uncompressed_size', sa.Integer(), nullable=False),
    sa.Column('has_blob_refs', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('cache_key', 'created_at')
    )
    op.create_index('idx_module_expires', 'analysis_result_cache', ['module_name', 'expires_at'], unique=False)
    op.create_index(op.f('ix_analysis_result_cache_expires_at'), 'analysis_result_cache', ['expires_at'], unique=False)
    op.create_table('blob_refs',
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('referrer_kind', sa.String(length=32), nullable=False),
    sa.Column('referrer_id', sa.String(length=128), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.PrimaryKeyConstraint('sha256', 'referrer_kind', 'referrer_id', 'created_at')
    )
    op.create_index('idx_by_referrer', 'blob_refs', ['referrer_kind', 'referrer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # Intentionally irreversible. This is the initial-schema revision for the
    # analysis result cache database, so there is nothing to revert to. Running it would DROP
    # every table -- and on a database that upgrade() merely stamped (a
    # pre-alembic deployment) that destroys live production data rather than
    # reverting a change. Refuse to run instead of risking that.
    raise RuntimeError(
        "refusing to downgrade the initial analysis result cache schema: it would drop the "
        "entire analysis result cache database. If you really need to tear it down, do it "
        "manually and restore from backup."
    )
