from saq.monitor import Monitor

MONITOR_TEST = Monitor(
    path="test",
    data_type=str,
    description="Used for unit testing."
)

MONITOR_DB_POOL_AVAILABLE_COUNT = Monitor(
    path="database.pool.available_count",
    data_type=int,
    description="The current number of available database connections in the pool."
)

MONITOR_DB_POOL_IN_USE_COUNT = Monitor(
    path="database.pool.in_use_count",
    data_type=int,
    description="The current number of database connections checked out from the pool."
)

MONITOR_SQLALCHEMY_DB_POOL_STATUS = Monitor(
    path="database.pool.status",
    data_type=str,
    description="The current status of the SQLAlchemy database pool."
)

MONITOR_ERROR_REPORT = Monitor(
    path="error.report",
    data_type=dict,
    description="Full exception stacktrace error report generated by ACE."
)
