from saq.monitor import Monitor

MONITOR_TEST = Monitor(
    path="test",
    data_type=str,
    description="Used for unit testing."
)

MONITOR_DB_POOL_AVAILABLE_COUNT = Monitor(
    path="database.pool.available_count",
    data_type=int,
    description="The current number of available database connections in the pool."
)

MONITOR_DB_POOL_IN_USE_COUNT = Monitor(
    path="database.pool.in_use_count",
    data_type=int,
    description="The current number of database connections checked out from the pool."
)

MONITOR_SQLALCHEMY_DB_POOL_STATUS = Monitor(
    path="database.pool.status",
    data_type=str,
    description="The current status of the SQLAlchemy database pool."
)

MONITOR_ERROR_REPORT = Monitor(
    path="error.report",
    data_type=dict,
    description="Full exception stacktrace error report generated by ACE."
)

MONITOR_MODULE_CRASH = Monitor(
    path="error.module_crash",
    data_type=dict,
    description="An analysis module crashed (raised, timed out, or took its worker down). Carries the crash report metadata, including the crash_id needed to download the report."
)

MONITOR_DISTRIBUTED_WORKLOAD = Monitor(
    path="workload.distributed",
    data_type=dict,
    description="Distributed workload counts by analysis mode."
)

MONITOR_LOCAL_WORKLOAD = Monitor(
    path="workload.local",
    data_type=dict,
    description="Local workload counts by type and mode."
)

MONITOR_DISTRIBUTED_DELAYED_ANALYSIS = Monitor(
    path="workload.distributed.delayed_analysis",
    data_type=dict,
    description="Single delayed analysis entry from the distributed workload."
)

MONITOR_DISTRIBUTED_LOCKS = Monitor(
    path="workload.distributed.locks",
    data_type=dict,
    description="Single lock entry from the distributed workload."
)

MONITOR_NODE_STATUS = Monitor(
    path="node.status",
    data_type=dict,
    description="Status and operator intent for a single node in the cluster."
)

MONITOR_CAS_POOL = Monitor(
    path="cas.pool",
    data_type=dict,
    description="Index state of one content-addressed storage pool: objects and bytes by state, holds, verify coverage, purges and objects GC should already have removed (docs/CAS.md)."
)

MONITOR_CAS_NODE = Monitor(
    path="cas.node",
    data_type=dict,
    description="Node-local content-addressed storage state: the read cache's size and the free space under the read cache and each local-backend pool."
)

MONITOR_CAS_GC = Monitor(
    path="cas.gc",
    data_type=dict,
    description="The outcome of one GC run over one content-addressed storage pool."
)

MONITOR_CAS_VERIFY = Monitor(
    path="cas.verify",
    data_type=dict,
    description="The outcome of one verify run over one content-addressed storage pool."
)

MONITOR_CAS_ORPHANS = Monitor(
    path="cas.orphans",
    data_type=dict,
    description="The outcome of one orphan sweep over one content-addressed storage pool."
)

MONITOR_CAS_INTEGRITY = Monitor(
    path="error.cas_integrity",
    data_type=dict,
    description="A content-addressed storage object failed verification (corrupt, wrong key) or its index row points at bytes that are gone."
)
