"""add analysis_module_crashes

Index of the analysis module crash reports written under <data_dir>/crash_reports, so an
analyst can find a crash report (and learn which node holds it) without already knowing its
id. The filesystem remains authoritative -- see saq/crash_report.py.

NOTE: autogenerate also proposed rewriting the idx_erc_collector_loop and
idx_file_collection_collector_loop indexes. That is pre-existing drift -- alembic renders
the DESC component of those composite indexes differently than the reflected schema
reports it -- and is unrelated to this change, so it is deliberately not included here.

Revision ID: 164ce1e2b5fb
Revises: 5aae036721d0
Create Date: 2026-09-16 18:11:29.080887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '164ce1e2b5fb'
down_revision: Union[str, None] = '5aae036721d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_module_crashes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('insert_date', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('crash_type', sa.Enum('exception', 'timeout', 'killed'), nullable=False),
    sa.Column('node', sa.String(length=1024), nullable=False),
    sa.Column('report_dir', sa.String(length=1024), nullable=False),
    sa.Column('module_path', sa.String(length=1024), nullable=True),
    sa.Column('module_name', sa.String(length=512), nullable=True),
    sa.Column('analysis_mode', sa.String(length=256), nullable=True),
    sa.Column('root_uuid', sa.String(length=36), nullable=True),
    sa.Column('observable_uuid', sa.String(length=36), nullable=True),
    sa.Column('observable_type', sa.String(length=64), nullable=True),
    sa.Column('observable_value', sa.Text(), nullable=True),
    sa.Column('exception_type', sa.String(length=256), nullable=True),
    sa.Column('exception_message', sa.Text(), nullable=True),
    sa.Column('has_file', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('i_module_crash_insert_date', 'analysis_module_crashes', ['insert_date'], unique=False)
    op.create_index('i_module_crash_module', 'analysis_module_crashes', ['module_path'], unique=False, mysql_length={'module_path': 255})
    op.create_index('i_module_crash_root_uuid', 'analysis_module_crashes', ['root_uuid'], unique=False)
    op.create_index('i_module_crash_uuid', 'analysis_module_crashes', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('i_module_crash_uuid', table_name='analysis_module_crashes')
    op.drop_index('i_module_crash_root_uuid', table_name='analysis_module_crashes')
    op.drop_index('i_module_crash_module', table_name='analysis_module_crashes', mysql_length={'module_path': 255})
    op.drop_index('i_module_crash_insert_date', table_name='analysis_module_crashes')
    op.drop_table('analysis_module_crashes')
    # ### end Alembic commands ###
