"""alert queue changes

Revision ID: 24c95edf1308
Revises: a6dc84e5be1b
Create Date: 2026-10-03 13:22:46.787342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '24c95edf1308'
down_revision: Union[str, None] = 'a6dc84e5be1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_queue_changes',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('from_queue', sa.String(length=64), nullable=False),
    sa.Column('to_queue', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.String(length=1024), nullable=False),
    sa.Column('router', sa.String(length=64), nullable=True),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('changed_at', mysql.TIMESTAMP(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alert_queue_changes_alert_id', 'alert_queue_changes', ['alert_id', 'id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # dropping the table drops its indexes; dropping ix_alert_queue_changes_alert_id first fails,
    # because the alert_id foreign key needs an index that starts with alert_id (MySQL 1553)
    op.drop_table('alert_queue_changes')
    # ### end Alembic commands ###
