"""add SUPERSEDED external remediation check result

Revision ID: 3c0e5d7a54f1
Revises: e306fdfac658
Create Date: 2026-08-19 14:53:20.349740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3c0e5d7a54f1'
down_revision: Union[str, None] = 'e306fdfac658'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # adds the SUPERSEDED value: another probe (or ACE itself) confirmed remediation of the same
    # target first, so this row was finalized without further vendor polling. (The autogenerated
    # idx_*_collector_loop index churn was removed -- those are the DESC literal-column indexes
    # alembic autogenerate cannot represent stably; the schema is unchanged.)
    op.alter_column('external_remediation_check', 'result',
               existing_type=mysql.ENUM('CONFIRMED', 'NOT_FOUND', 'EXPIRED', 'ERROR', 'CANCELLED', collation='utf8mb4_unicode_520_ci'),
               type_=sa.Enum('CONFIRMED', 'NOT_FOUND', 'EXPIRED', 'ERROR', 'CANCELLED', 'SUPERSEDED'),
               existing_nullable=True)


def downgrade() -> None:
    # SUPERSEDED rows must be remapped before the enum narrows or MySQL rejects the alter
    op.execute("UPDATE external_remediation_check SET result = 'EXPIRED' WHERE result = 'SUPERSEDED'")
    op.alter_column('external_remediation_check', 'result',
               existing_type=sa.Enum('CONFIRMED', 'NOT_FOUND', 'EXPIRED', 'ERROR', 'CANCELLED', 'SUPERSEDED'),
               type_=mysql.ENUM('CONFIRMED', 'NOT_FOUND', 'EXPIRED', 'ERROR', 'CANCELLED', collation='utf8mb4_unicode_520_ci'),
               existing_nullable=True)
