"""svs yara captures

The YARA samples SVS captures from dispositioned alerts (docs/SVS.md, Part 2; saq/svs/capture.py).
No foreign key to alerts: a capture outlives its alert, so that its CAS holds are released only
when the capture itself is removed.

Revision ID: 4ba5a47774b4
Revises: 6cacb4157914
Create Date: 2026-10-05 18:02:11.478527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4ba5a47774b4'
down_revision: Union[str, None] = '6cacb4157914'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('svs_yara_captures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_uuid', sa.String(length=36), nullable=False),
    sa.Column('observable_uuid', sa.String(length=36), nullable=False),
    sa.Column('sha256', sa.CHAR(length=64), nullable=False),
    sa.Column('rule_uuid', sa.String(length=36), nullable=False),
    sa.Column('rule_name', sa.String(length=256), nullable=False),
    sa.Column('namespace', sa.String(length=256), nullable=True),
    sa.Column('signature_version', sa.String(length=64), nullable=False),
    sa.Column('rule_content_hash', sa.CHAR(length=64), nullable=True),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('yara_meta_tags', sa.Text(), nullable=True),
    sa.Column('record_digest', sa.CHAR(length=64), nullable=True),
    sa.Column('match_summary', mysql.MEDIUMTEXT(), nullable=True),
    sa.Column('yara_python_version', sa.String(length=32), nullable=True),
    sa.Column('yara_scanner_version', sa.String(length=32), nullable=True),
    sa.Column('node', sa.String(length=1024), nullable=False),
    sa.Column('state', sa.Enum('pending', 'stored', 'missing'), nullable=False),
    sa.Column('missing_reason', sa.Enum('file', 'match_record', 'storage'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('stored_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alert_uuid', 'sha256', 'rule_uuid', name='uq_svs_yara_captures_alert_sample')
    )
    op.create_index('i_svs_yara_captures_rule_missing', 'svs_yara_captures', ['rule_uuid', 'missing_reason'], unique=False)
    op.create_index('i_svs_yara_captures_sample', 'svs_yara_captures', ['sha256', 'rule_uuid'], unique=False)
    op.create_index(op.f('ix_svs_yara_captures_updated_at'), 'svs_yara_captures', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_svs_yara_captures_updated_at'), table_name='svs_yara_captures')
    op.drop_index('i_svs_yara_captures_sample', table_name='svs_yara_captures')
    op.drop_index('i_svs_yara_captures_rule_missing', table_name='svs_yara_captures')
    op.drop_table('svs_yara_captures')
    # ### end Alembic commands ###
