"""add cas tables

The index of the content-addressed storage subsystem (docs/CAS.md): cas_objects is authoritative
for which objects exist, cas_holds are the explicit references that keep them alive, cas_purges
audits forced deletions. Only saq/cas/index.py writes these tables.

Autogenerated. The DESC-index drift on external_remediation_check and file_collection that
autogenerate keeps proposing (see 164ce1e2b5fb) was removed from this revision by hand; it is not
part of this change.

Revision ID: 56cafaed6b55
Revises: 164ce1e2b5fb
Create Date: 2026-09-27 16:58:41.908760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56cafaed6b55'
down_revision: Union[str, None] = '164ce1e2b5fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table('cas_objects',
    sa.Column('pool', sa.String(length=64), nullable=False),
    sa.Column('digest', sa.CHAR(length=64), nullable=False),
    sa.Column('size', sa.BigInteger(), nullable=False),
    sa.Column('stored_size', sa.BigInteger(), nullable=False),
    sa.Column('key_id', sa.String(length=32), nullable=True),
    sa.Column('state', sa.Enum('present', 'deleting'), server_default=sa.text("'present'"), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('last_held_at', sa.DateTime(), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('pool', 'digest')
    )
    op.create_index('i_cas_objects_gc', 'cas_objects', ['pool', 'state', 'last_held_at'], unique=False)
    op.create_table('cas_purges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pool', sa.String(length=64), nullable=False),
    sa.Column('digest', sa.CHAR(length=64), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=True),
    sa.Column('purged_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('i_cas_purges_object', 'cas_purges', ['pool', 'digest'], unique=False)
    op.create_table('cas_holds',
    sa.Column('pool', sa.String(length=64), nullable=False),
    sa.Column('digest', sa.CHAR(length=64), nullable=False),
    sa.Column('holder_kind', sa.String(length=32), nullable=False),
    sa.Column('holder_id', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['pool', 'digest'], ['cas_objects.pool', 'cas_objects.digest'], name='fk_cas_holds_object', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pool', 'digest', 'holder_kind', 'holder_id')
    )
    op.create_index('i_cas_holds_holder', 'cas_holds', ['pool', 'holder_kind', 'holder_id'], unique=False)


def downgrade() -> None:
    op.drop_index('i_cas_holds_holder', table_name='cas_holds')
    op.drop_table('cas_holds')
    op.drop_index('i_cas_purges_object', table_name='cas_purges')
    op.drop_table('cas_purges')
    op.drop_index('i_cas_objects_gc', table_name='cas_objects')
    op.drop_table('cas_objects')
