"""drop messaging tables

Revision ID: 5b4a542b4b7b
Revises: fcc3af620f80
Create Date: 2026-09-29 18:46:44.124707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5b4a542b4b7b'
down_revision: Union[str, None] = 'fcc3af620f80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message_routing')
    op.drop_table('messages')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('content', mysql.TEXT(collation='utf8mb4_unicode_520_ci'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_520_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('message_routing',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('message_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('route', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=64), nullable=False),
    sa.Column('destination', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=256), nullable=False),
    sa.Column('lock', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=36), nullable=True),
    sa.Column('lock_time', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('message_routing_ibfk_1'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_520_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('idx_message_routing_mrd'), 'message_routing', ['message_id', 'route', 'destination'], unique=False)
    # ### end Alembic commands ###
