"""detection point verdicts

Revision ID: 6cacb4157914
Revises: d22acc09af22
Create Date: 2026-10-05 12:56:43.103166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6cacb4157914'
down_revision: Union[str, None] = 'd22acc09af22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detection_point_verdict_history',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('signature_uuid', sa.String(length=36), nullable=False),
    sa.Column('old_verdict', sa.Enum('tp', 'fp'), nullable=True),
    sa.Column('new_verdict', sa.Enum('tp', 'fp'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('changed_at', mysql.TIMESTAMP(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_detection_point_verdict_history_detection', 'detection_point_verdict_history', ['alert_id', 'content_hash', 'changed_at'], unique=False)
    op.create_table('detection_point_verdicts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('signature_uuid', sa.String(length=36), nullable=False),
    sa.Column('verdict', sa.Enum('tp', 'fp'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('set_at', mysql.TIMESTAMP(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alert_id', 'content_hash', name='uq_detection_point_verdicts_alert_content')
    )
    op.create_index(op.f('ix_detection_point_verdicts_signature_uuid'), 'detection_point_verdicts', ['signature_uuid'], unique=False)
    op.create_index('ix_detection_points_alert_signature', 'detection_points', ['alert_id', 'signature_uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_detection_points_alert_signature', table_name='detection_points')
    op.drop_index(op.f('ix_detection_point_verdicts_signature_uuid'), table_name='detection_point_verdicts')
    op.drop_table('detection_point_verdicts')
    # the table's (alert_id, ...) index backs its alert_id foreign key, so MySQL refuses to drop it
    # on its own (1553); dropping the table drops it
    op.drop_table('detection_point_verdict_history')
    # ### end Alembic commands ###
