"""saved filters per screen

Revision ID: a4d56a2c4171
Revises: a7c2e41d9b35
Create Date: 2026-10-02 20:23:39.242024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4d56a2c4171'
down_revision: Union[str, None] = 'a7c2e41d9b35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saved_filters', sa.Column('screen', sa.String(length=32), server_default=sa.text("'alerts'"), nullable=False))
    # the new user_id-leading indexes are created BEFORE the old ones are dropped: the
    # user_id foreign key needs an index that starts with user_id at every step (MySQL 1553)
    op.create_index('i_saved_filter_user_screen_kind', 'saved_filters', ['user_id', 'screen', 'kind'], unique=False)
    op.create_index('i_saved_filter_user_screen_quick', 'saved_filters', ['user_id', 'screen', 'quick_filter_order'], unique=False)
    op.create_unique_constraint('uq_saved_filter_user_screen_name', 'saved_filters', ['user_id', 'screen', 'name'])
    op.drop_index(op.f('i_saved_filter_user_kind'), table_name='saved_filters')
    op.drop_index(op.f('i_saved_filter_user_quick'), table_name='saved_filters')
    op.drop_index(op.f('uq_saved_filter_user_name'), table_name='saved_filters')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # before this revision saved filters existed only for the alert screen, and the old
    # (user_id, name) unique key cannot hold one name used on two screens
    op.execute("DELETE FROM saved_filters WHERE screen != 'alerts'")
    op.create_index(op.f('uq_saved_filter_user_name'), 'saved_filters', ['user_id', 'name'], unique=True)
    op.create_index(op.f('i_saved_filter_user_quick'), 'saved_filters', ['user_id', 'quick_filter_order'], unique=False)
    op.create_index(op.f('i_saved_filter_user_kind'), 'saved_filters', ['user_id', 'kind'], unique=False)
    op.drop_constraint('uq_saved_filter_user_screen_name', 'saved_filters', type_='unique')
    op.drop_index('i_saved_filter_user_screen_quick', table_name='saved_filters')
    op.drop_index('i_saved_filter_user_screen_kind', table_name='saved_filters')
    op.drop_column('saved_filters', 'screen')
    # ### end Alembic commands ###
