"""alerts updated_at

Revision ID: a6dc84e5be1b
Revises: a4d56a2c4171
Create Date: 2026-10-02 20:57:21.327196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a6dc84e5be1b'
down_revision: Union[str, None] = 'a4d56a2c4171'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('updated_at', mysql.TIMESTAMP(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)'), nullable=False))
    op.create_index(op.f('ix_alerts_updated_at'), 'alerts', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alerts_updated_at'), table_name='alerts')
    op.drop_column('alerts', 'updated_at')
    # ### end Alembic commands ###
