"""detection point node identity

Revision ID: d22acc09af22
Revises: 24c95edf1308
Create Date: 2026-10-05 12:00:29.023322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd22acc09af22'
down_revision: Union[str, None] = '24c95edf1308'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detection_points', sa.Column('signature_family', sa.String(length=32), nullable=True))
    op.add_column('detection_points', sa.Column('node_kind', sa.String(length=16), nullable=True))
    op.add_column('detection_points', sa.Column('node_type', sa.String(length=64), nullable=True))
    op.add_column('detection_points', sa.Column('node_value_sha256', sa.String(length=64), nullable=True))
    op.add_column('detection_points', sa.Column('node_module_path', sa.String(length=512, collation='utf8mb4_bin'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('detection_points', 'node_module_path')
    op.drop_column('detection_points', 'node_value_sha256')
    op.drop_column('detection_points', 'node_type')
    op.drop_column('detection_points', 'node_kind')
    op.drop_column('detection_points', 'signature_family')
    # ### end Alembic commands ###
