"""yara qa tables

yara_qa_signatures (per signature uuid and version counters) and yara_qa_matches (one row per file
stored for a YARA rule in QA mode, whose bytes and match record are held in the yara_qa CAS pool).
See docs/YARA_QA.md.

Revision ID: d3f648d96551
Revises: 5b4a542b4b7b
Create Date: 2026-09-30 15:00:51.144007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd3f648d96551'
down_revision: Union[str, None] = '5b4a542b4b7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('yara_qa_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('signature_uuid', sa.String(length=36), nullable=False),
    sa.Column('signature_version', sa.String(length=64), nullable=False),
    sa.Column('sha256', sa.CHAR(length=64), nullable=False),
    sa.Column('file_name', sa.String(length=1024), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('root_uuid', sa.String(length=36), nullable=False),
    sa.Column('observable_uuid', sa.String(length=36), nullable=False),
    sa.Column('node', sa.String(length=1024), nullable=False),
    sa.Column('match_digest', sa.CHAR(length=64), nullable=True),
    sa.Column('match_summary', mysql.MEDIUMTEXT(), nullable=True),
    sa.Column('hit_count', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('first_seen', sa.DateTime(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('signature_uuid', 'signature_version', 'sha256', name='uq_yara_qa_matches_file')
    )
    op.create_index('i_yara_qa_matches_expires', 'yara_qa_matches', ['expires_at', 'id'], unique=False)
    op.create_index('i_yara_qa_matches_signature', 'yara_qa_matches', ['signature_uuid', 'id'], unique=False)
    op.create_table('yara_qa_signatures',
    sa.Column('signature_uuid', sa.String(length=36), nullable=False),
    sa.Column('signature_version', sa.String(length=64), nullable=False),
    sa.Column('rule_name', sa.String(length=256), nullable=False),
    sa.Column('namespace', sa.String(length=256), nullable=True),
    sa.Column('match_count', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('stored_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('first_match_at', sa.DateTime(), nullable=False),
    sa.Column('last_match_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('signature_uuid', 'signature_version')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('yara_qa_signatures')
    op.drop_index('i_yara_qa_matches_signature', table_name='yara_qa_matches')
    op.drop_index('i_yara_qa_matches_expires', table_name='yara_qa_matches')
    op.drop_table('yara_qa_matches')
    # ### end Alembic commands ###
