"""multiple scoped api keys per user

Revision ID: e306fdfac658
Revises: c3f9a1d47b20
Create Date: 2026-08-06 18:30:35.883754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e306fdfac658'
down_revision: Union[str, None] = 'c3f9a1d47b20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_api_key',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('inherit_user_scope', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    op.create_index('i_api_key_user', 'auth_api_key', ['user_id'], unique=False)
    op.create_table('auth_api_key_permission',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('api_key_id', sa.BigInteger(), nullable=False),
    sa.Column('major', sa.String(length=512, collation='ascii_general_ci'), nullable=False),
    sa.Column('minor', sa.String(length=512, collation='ascii_general_ci'), nullable=False),
    sa.Column('effect', sa.Enum('ALLOW', 'DENY'), server_default=sa.text("'ALLOW'"), nullable=False),
    sa.ForeignKeyConstraint(['api_key_id'], ['auth_api_key.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_key_id', 'major', 'minor', 'effect', name='u_api_key_perm')
    )
    op.create_index('i_api_key_major_minor', 'auth_api_key_permission', ['api_key_id', 'major', 'minor'], unique=False)

    # Backfill: carry every existing single user key forward as an inherit-scoped "primary" key so
    # currently-configured keys keep authenticating (no flag-day re-key). Only the hash migrates --
    # the old recoverable apikey_encrypted copies are intentionally dropped, not carried.
    op.execute(
        "INSERT INTO auth_api_key (user_id, name, key_hash, inherit_user_scope, created_at) "
        "SELECT id, 'primary', apikey_hash, 1, NOW() FROM users WHERE apikey_hash IS NOT NULL"
    )

    op.drop_index(op.f('apikey_hash'), table_name='users')
    op.drop_column('users', 'apikey_encrypted')
    op.drop_column('users', 'apikey_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('apikey_hash', mysql.VARCHAR(collation='utf8mb4_unicode_520_ci', length=64), nullable=True))
    op.add_column('users', sa.Column('apikey_encrypted', sa.BLOB(), nullable=True))
    op.create_index(op.f('apikey_hash'), 'users', ['apikey_hash'], unique=True)

    # Best-effort restore of the single-key column from an inherit "primary" key. The encrypted copy
    # cannot be reconstructed (it was never stored), so apikey_encrypted stays NULL.
    op.execute(
        "UPDATE users u JOIN auth_api_key k ON k.user_id = u.id AND k.name = 'primary' "
        "SET u.apikey_hash = k.key_hash"
    )

    op.drop_index('i_api_key_major_minor', table_name='auth_api_key_permission')
    op.drop_table('auth_api_key_permission')
    op.drop_index('i_api_key_user', table_name='auth_api_key')
    op.drop_table('auth_api_key')
    # ### end Alembic commands ###
