"""add analysis_types and analysis_mapping

Revision ID: fcc3af620f80
Revises: 61b26390b94e
Create Date: 2026-09-29 12:49:10.382777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcc3af620f80'
down_revision: Union[str, None] = '61b26390b94e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_path', sa.String(length=512, collation='utf8mb4_bin'), nullable=False),
    sa.Column('display_name', sa.String(length=512), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('module_path')
    )
    op.create_table('analysis_mapping',
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('analysis_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['analysis_type_id'], ['analysis_types.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('alert_id', 'analysis_type_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('analysis_mapping')
    op.drop_table('analysis_types')
    # ### end Alembic commands ###
