"""scope incoming_workload by node

Revision ID: ff80700a9518
Revises: 4ceec152b520
Create Date: 2026-09-08 20:28:42.203693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff80700a9518'
down_revision: Union[str, None] = '4ceec152b520'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

FK_NAME = 'fk_incoming_workload_node_id'


def upgrade() -> None:
    # collectors used to track their workload in a node-local database (database_collection).
    # that workload now lives here, scoped by node_id, so any rows already present cannot be
    # attributed to a node. undelivered work is discarded -- collectors must be drained before
    # upgrading, and the matching directories under the collection incoming_dir removed by hand.
    # this cascades to work_distribution.
    op.execute("DELETE FROM incoming_workload")

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incoming_workload', sa.Column('node_id', sa.Integer(), nullable=False))
    # created before the foreign key so that MySQL uses it to satisfy the key's index
    # requirement instead of auto-creating a redundant single-column index on node_id
    op.create_index('idx_iw_node_type', 'incoming_workload', ['node_id', 'type_id'], unique=False)
    op.create_foreign_key(FK_NAME, 'incoming_workload', 'nodes', ['node_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(FK_NAME, 'incoming_workload', type_='foreignkey')
    op.drop_index('idx_iw_node_type', table_name='incoming_workload')
    op.drop_column('incoming_workload', 'node_id')
    # ### end Alembic commands ###
