import base64
import logging
import os

import yaml

from saq.configuration.error import EncryptedPasswordError
from saq.environment import get_global_runtime_settings

def export_encrypted_passwords():
    """Returns a JSON dict of all the encrypted passwords with decrypted values."""
    from saq.database import get_db_connection
    from saq.configuration.config import get_config
    with get_db_connection(name=get_config().global_settings.encrypted_passwords_db) as db:
        c = db.cursor()
        c.execute("""
SELECT
    `key`, `encrypted_value`
FROM
    `encrypted_passwords`
ORDER BY
    `key`""")
        export = {}
        for row in c:
            #logging.info(f"exporting password for {row[0]}")
            try:
                export[row[0]] = decrypt_password(row[0])
            except EncryptedPasswordError:
                export[row[0]] = None

        return export

def import_encrypted_passwords(export):
    """Imports the JSON dict generated by export_encrypted_passwords."""
    for key, value in export.items():
        logging.info(f"importing password for {key}")
        encrypt_password(key, value)

def list_encrypted_password_keys():
    """Returns a sorted list of the stored encrypted-password key names.

    Unlike export_encrypted_passwords(), this never decrypts anything -- it is safe to call from a
    write-only management surface that must not surface plaintext secret values.
    """
    from saq.database import get_db_connection
    from saq.configuration.config import get_config
    with get_db_connection(name=get_config().global_settings.encrypted_passwords_db) as db:
        c = db.cursor()
        c.execute("SELECT `key` FROM `encrypted_passwords` ORDER BY `key`")
        return [row[0] for row in c]

def _collect_encrypted_references(value, references):
    """Recursively add every ``encrypted:<name>`` marker in *value* to the *references* set."""
    # keep the literal in sync with yaml_parser.ENCRYPTED_PREFIX (importing it would create an
    # encryption -> yaml_parser -> encryption import cycle)
    encrypted_prefix = "encrypted:"
    if isinstance(value, dict):
        for item in value.values():
            _collect_encrypted_references(item, references)
    elif isinstance(value, list):
        for item in value:
            _collect_encrypted_references(item, references)
    elif isinstance(value, str) and value.startswith(encrypted_prefix):
        references.add(value[len(encrypted_prefix):])

def find_encrypted_config_references():
    """Returns the set of secret names *declared* as ``encrypted:<name>`` in any loaded config file.

    A name is "referenced" if *any* config file this node loaded declares ``encrypted:<name>``. We
    scan each loaded file's raw YAML **independently** and union the results, rather than merging or
    walking the live config, and that distinction matters:

    - The live config (``get_config().raw._data``) can't be used here: ``resolve_all_values`` resolves
      every ``encrypted:`` marker away in place at startup, so set secrets and, in some load orders,
      unset ones leave no marker behind. (See find_effective_encrypted_config_references, which uses
      exactly that property to detect plaintext overrides.)
    - Re-merging the loaded files into one parser is order-dependent -- ``loaded_files`` is a set, and
      a later-merged file (e.g. a dev override that pins an integration's key to a literal value)
      silently replaces an earlier ``encrypted:`` marker, so the result flips with iteration order.

    Scanning per file avoids both: it is deterministic and surfaces every secret name the config asks
    for, which is exactly what the management UI needs. ``loaded_files`` is the exact set this process
    loaded -- default, integration configs, command-line files, and ``config:`` includes alike.
    """
    from saq.configuration.config import get_config
    references = set()
    for path in get_config().raw.loaded_files:
        if not os.path.exists(path):
            continue
        try:
            with open(path, "r", encoding="utf-8") as f:
                # raw YAML only: no merge, no encrypted:/env:/file: resolution, so markers survive
                _collect_encrypted_references(yaml.load(f, Loader=yaml.SafeLoader), references)
        except Exception as e:
            logging.warning(f"unable to scan config file {path} for encrypted references: {e}")

    return references

def find_effective_encrypted_config_references():
    """Returns the secret names whose ``encrypted:<name>`` marker survives in the *effective* config.

    Walks the live merged config (``get_config().raw._data``), which reflects the real load order and
    has had ``resolve_all_values`` applied. A marker survives there only when the effective value at
    that key is still ``encrypted:<name>`` -- i.e. no later-loaded file overrode it with a literal,
    and the secret was not resolved to a stored value.

    Compared against find_encrypted_config_references(), this is how a plaintext override is detected:
    a name that is *declared* but does not appear here, and is not set in the store, has had its
    marker masked by a later-loaded plaintext value (an unset secret's marker otherwise survives
    resolution untouched, since decryption of a missing secret is a no-op).
    """
    from saq.configuration.config import get_config
    references = set()
    _collect_encrypted_references(get_config().raw._data, references)
    return references

def encrypt_password(key, value):
    """Stores sensitive data as an encrypted value."""
    from saq.crypto import encrypt_chunk
    from saq.configuration.config import get_config
    encrypted_value = base64.b64encode(encrypt_chunk(value.encode('utf8')))

    from saq.database import get_db_connection
    with get_db_connection(name=get_config().global_settings.encrypted_passwords_db) as db:
        c = db.cursor()
        c.execute("""
INSERT INTO `encrypted_passwords` ( `key`, `encrypted_value` )
VALUES ( %s, %s )
ON DUPLICATE KEY UPDATE
    `encrypted_value` = %s""", ( key, encrypted_value, encrypted_value ))
        db.commit()

def delete_password(key):
    """Deletes the given password from the database. Returns True if the password was deleted."""
    from saq.database import get_db_connection
    from saq.configuration.config import get_config
    with get_db_connection(name=get_config().global_settings.encrypted_passwords_db) as db:
        c = db.cursor()
        c.execute("DELETE FROM `encrypted_passwords` WHERE `key` = %s", (key,))
        db.commit()
        return c.rowcount == 1

def decrypt_password(key):
    """Returns the decrypted value for the given key."""
    from saq.database import get_db_connection
    from saq.configuration.config import get_config
    with get_db_connection(name=get_config().global_settings.encrypted_passwords_db) as db:
        c = db.cursor()
        c.execute("""
SELECT 
    `encrypted_value`
FROM
    `encrypted_passwords`
WHERE
    `key` = %s
""", (key,))
        row = c.fetchone()
        if row is None:
            logging.warning(f"request for unknown encrypted password {key}")
            return None

        if get_global_runtime_settings().encryption_key:
            from saq.crypto import decrypt_chunk
            return decrypt_chunk(base64.b64decode(row[0])).decode('utf8')
        else:
            logging.error(f"request to decrypt {key} without decryption key set")
            return None
            #raise EncryptedPasswordError(key=key)
