#!/usr/bin/env bash
source /opt/ace/bin/initialize-environment.sh

DATA_DIR=$(ace config -v global.data_dir)
if [ -z "$DATA_DIR" ] || [ ! -d "$DATA_DIR" ]; then
    echo "invalid data directory \"$DATA_DIR\""
    exit 1
fi

# delete submission error debug info older than 14 days
if [ -d "$DATA_DIR/var/collection/error" ]; then
    find "$DATA_DIR/var/collection/error" -type f -mtime +14 -delete
fi
