"""initial schema

Revision ID: fe7816547cc7
Revises:
Create Date: 2026-07-31 12:10:33.300201

Brings the brocess database under alembic. Before this revision brocess was
created from the table DDL in sql/03-brocess.sql and changed by hand-written
one-off ALTER scripts (one of which, sql/tools/alter_email_thread_domain_message_id.sql,
has since gone missing from the repo).

This revision has to upgrade cleanly against three different starting states:

  1. a fresh empty database (new deployments, unit test databases)
  2. a complete pre-alembic database (production)
  3. a partial pre-alembic database -- e.g. one predating the email_thread_*
     tables, or one that never had the missing ALTER applied

So instead of the information_schema sentinel used by the initial revision of
the ace chain (alembic/ace/versions/88d97a42fbef_initial_schema.py), every
create here is conditional -- if_not_exists for tables, and an
information_schema guard for indexes, since MySQL has no
CREATE INDEX IF NOT EXISTS. That is a deliberate one-off deviation: it makes
case 3 self-heal rather than being silently stamped and left broken.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'fe7816547cc7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# legacy index name -> new name, applied to both connerr and connlog
INDEX_RENAMES = (
    ('sourceip', 'idx_sourceip_destip'),
    ('sourceip_2', 'idx_sourceip'),
    ('destip', 'idx_destip'),
)


def _index_exists(conn, table: str, index: str) -> bool:
    return bool(conn.execute(sa.text(
        "SELECT COUNT(*) FROM information_schema.statistics "
        "WHERE table_schema = DATABASE() AND table_name = :t AND index_name = :i"
    ), {"t": table, "i": index}).scalar())


def _column_type(conn, table: str, column: str) -> str:
    return conn.execute(sa.text(
        "SELECT data_type FROM information_schema.columns "
        "WHERE table_schema = DATABASE() AND table_name = :t AND column_name = :c"
    ), {"t": table, "c": column}).scalar() or ""


def _create_index_if_missing(conn, name: str, table: str, columns: list) -> None:
    """op.create_index, skipped when the index is already there.

    MySQL has no CREATE INDEX IF NOT EXISTS -- alembic will happily accept
    if_not_exists=True on create_index and then emit DDL the server rejects with
    a syntax error. Guard against information_schema instead.
    """
    if not _index_exists(conn, table, name):
        op.create_index(name, table, columns, unique=False)


def upgrade() -> None:
    conn = op.get_bind()

    # --- reconcile pre-existing connerr/connlog -------------------------------
    # this must run BEFORE the create_index calls below: on a pre-existing table
    # the old index is still named `sourceip`/`destip`, so a create_index for
    # `idx_sourceip`/`idx_destip` would not find a conflict and would build a
    # second, duplicate index. renaming first makes the creates true no-ops.
    # all of this is a no-op on a fresh database.
    for table in ('connerr', 'connlog'):
        for old_name, new_name in INDEX_RENAMES:
            if _index_exists(conn, table, old_name) and not _index_exists(conn, table, new_name):
                op.execute(f"ALTER TABLE `{table}` RENAME INDEX `{old_name}` TO `{new_name}`")

    if _column_type(conn, 'connerr', 'numconnections') == 'int':
        op.execute("ALTER TABLE `connerr` MODIFY `numconnections` BIGINT NULL")

    # --- drop the unused properties table ------------------------------------
    op.execute("DROP TABLE IF EXISTS `properties`")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connerr',
    sa.Column('sourceip', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('destip', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('destport', sa.Integer(), nullable=False),
    sa.Column('numconnections', sa.BigInteger(), nullable=True),
    sa.Column('firstconnectdate', mysql.DOUBLE(), nullable=True),
    sa.PrimaryKeyConstraint('sourceip', 'destip', 'destport'),
    if_not_exists=True
    )
    _create_index_if_missing(conn, 'idx_destip', 'connerr', ['destip'])
    _create_index_if_missing(conn, 'idx_sourceip', 'connerr', ['sourceip'])
    _create_index_if_missing(conn, 'idx_sourceip_destip', 'connerr', ['sourceip', 'destip'])
    op.create_table('connlog',
    sa.Column('sourceip', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('destip', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('destport', sa.Integer(), nullable=False),
    sa.Column('numconnections', sa.BigInteger(), nullable=True),
    sa.Column('firstconnectdate', mysql.DOUBLE(), nullable=True),
    sa.PrimaryKeyConstraint('sourceip', 'destip', 'destport'),
    if_not_exists=True
    )
    _create_index_if_missing(conn, 'idx_destip', 'connlog', ['destip'])
    _create_index_if_missing(conn, 'idx_sourceip', 'connlog', ['sourceip'])
    _create_index_if_missing(conn, 'idx_sourceip_destip', 'connlog', ['sourceip', 'destip'])
    op.create_table('email_thread_domain',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('thread_id', sa.Text(), nullable=False),
    sa.Column('thread_id_hash', sa.BINARY(length=32), nullable=False),
    sa.Column('message_id_hash', sa.BINARY(length=32), nullable=True),
    sa.Column('domain', sa.Text(), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('entry_hash', sa.BINARY(length=32), nullable=False),
    sa.Column('numseen', sa.BigInteger(), server_default=sa.text('1'), nullable=True),
    sa.Column('firstseendate', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('thread_id_hash', 'entry_hash', name='uniq_thread_domain'),
    if_not_exists=True
    )
    _create_index_if_missing(conn, 'idx_thread', 'email_thread_domain', ['thread_id_hash'])
    op.create_table('email_thread_message',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('insert_date', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('thread_id', sa.Text(), nullable=False),
    sa.Column('thread_id_hash', sa.BINARY(length=32), nullable=False),
    sa.Column('message_id', sa.Text(), nullable=False),
    sa.Column('message_id_hash', sa.BINARY(length=32), nullable=False),
    sa.Column('in_reply_to', sa.Text(), nullable=True),
    sa.Column('normalized_subject', sa.Text(), nullable=True),
    sa.Column('normalized_subject_hash', sa.BINARY(length=32), nullable=True),
    sa.Column('from_address', sa.Text(), nullable=True),
    sa.Column('from_domain', sa.Text(), nullable=True),
    sa.Column('direction', mysql.TINYINT(), nullable=True),
    sa.Column('message_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('thread_id_hash', 'message_id_hash', name='uniq_thread_message'),
    if_not_exists=True
    )
    _create_index_if_missing(conn, 'idx_subject', 'email_thread_message', ['normalized_subject_hash'])
    _create_index_if_missing(conn, 'idx_thread_date', 'email_thread_message', ['thread_id_hash', 'message_date'])
    op.create_table('httplog',
    sa.Column('host', sa.VARBINARY(length=255), nullable=False),
    sa.Column('numconnections', sa.BigInteger(), nullable=True),
    sa.Column('firstconnectdate', mysql.DOUBLE(), nullable=True),
    sa.PrimaryKeyConstraint('host'),
    if_not_exists=True
    )
    op.create_table('smtplog',
    sa.Column('source', sa.VARBINARY(length=255), nullable=False),
    sa.Column('destination', sa.VARBINARY(length=255), nullable=False),
    sa.Column('numconnections', sa.BigInteger(), nullable=True),
    sa.Column('firstconnectdate', mysql.DOUBLE(), nullable=True),
    sa.PrimaryKeyConstraint('source', 'destination'),
    if_not_exists=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # WARNING: this drops the entire brocess database, including tables that
    # existed long before alembic did. On a deployment where upgrade() was a
    # no-op (a pre-alembic database that was simply stamped) this destroys live
    # data rather than reverting anything. The ace chain's initial revision has
    # the same property. It does not recreate `properties`, which is
    # intentionally gone, nor restore the legacy index names.
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('smtplog')
    op.drop_table('httplog')
    op.drop_index('idx_thread_date', table_name='email_thread_message')
    op.drop_index('idx_subject', table_name='email_thread_message')
    op.drop_table('email_thread_message')
    op.drop_index('idx_thread', table_name='email_thread_domain')
    op.drop_table('email_thread_domain')
    op.drop_index('idx_sourceip_destip', table_name='connlog')
    op.drop_index('idx_sourceip', table_name='connlog')
    op.drop_index('idx_destip', table_name='connlog')
    op.drop_table('connlog')
    op.drop_index('idx_sourceip_destip', table_name='connerr')
    op.drop_index('idx_sourceip', table_name='connerr')
    op.drop_index('idx_destip', table_name='connerr')
    op.drop_table('connerr')
    # ### end Alembic commands ###
