"""initial schema

Revision ID: a7a9e49023c2
Revises:
Create Date: 2026-07-31 15:39:58.450095

Brings the email-archive database under alembic. Before this revision the
schema was created from the table DDL in sql/02-email-archive.sql, and its
partitions were (and still are) managed out of band by
bin/manage-email-archive-partitions.sh on a weekly cron.

Like the brocess initial revision (alembic/brocess/versions/fe7816547cc7_initial_schema.py)
this has to upgrade cleanly against three different starting states:

  1. a fresh empty database (new deployments, unit test databases)
  2. a complete pre-alembic database (production)
  3. a partial pre-alembic database

so every create is conditional -- if_not_exists for tables and an
information_schema guard for indexes (MySQL has no CREATE INDEX IF NOT EXISTS).

Partitioning is the one thing autogenerate cannot express. archive,
archive_index and email_history are RANGE-partitioned by insert_date, seeded
with a single p_catchall MAXVALUE partition that the weekly cron script later
splits into pYYYYwWW partitions. We (re)establish only that initial p_catchall
structure here, and ONLY when the table currently has no partitions -- so a
production table that is already carrying live weekly partitions is left
completely alone. Re-issuing PARTITION BY on a populated table would REORGANIZE
every weekly partition back into the catchall and is never what we want.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a7a9e49023c2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# the three RANGE-partitioned tables (archive_server is intentionally excluded --
# it is not partitioned). Mirrors TABLES in bin/manage-email-archive-partitions.sh.
PARTITIONED_TABLES = ('archive', 'archive_index', 'email_history')


def _index_exists(conn, table: str, index: str) -> bool:
    return bool(conn.execute(sa.text(
        "SELECT COUNT(*) FROM information_schema.statistics "
        "WHERE table_schema = DATABASE() AND table_name = :t AND index_name = :i"
    ), {"t": table, "i": index}).scalar())


def _create_index_if_missing(conn, name: str, table: str, columns: list) -> None:
    """op.create_index, skipped when the index is already there.

    MySQL has no CREATE INDEX IF NOT EXISTS -- alembic will happily accept
    if_not_exists=True on create_index and then emit DDL the server rejects with
    a syntax error. Guard against information_schema instead.
    """
    if not _index_exists(conn, table, name):
        op.create_index(name, table, columns, unique=False)


def _partition_count(conn, table: str) -> int:
    """Number of real partitions on a table (0 for a non-partitioned table).

    A non-partitioned table has exactly one information_schema.partitions row
    with partition_name = NULL, so filtering to non-NULL names returns 0.
    """
    return int(conn.execute(sa.text(
        "SELECT COUNT(*) FROM information_schema.partitions "
        "WHERE table_schema = DATABASE() AND table_name = :t "
        "AND partition_name IS NOT NULL"
    ), {"t": table}).scalar() or 0)


def upgrade() -> None:
    conn = op.get_bind()

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('archive',
    sa.Column('archive_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.Column('hash', sa.BINARY(length=32), nullable=False),
    sa.Column('insert_date', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('archive_id', 'insert_date'),
    sa.UniqueConstraint('server_id', 'hash', 'insert_date', name='idx_server_id'),
    if_not_exists=True
    )
    _create_index_if_missing(conn, 'idx_insert_date', 'archive', ['insert_date'])
    op.create_table('archive_index',
    sa.Column('field', mysql.ENUM('env_from', 'env_to', 'body_from', 'body_to', 'subject', 'decoded_subject', 'message_id', 'content', 'url'), nullable=False),
    sa.Column('hash', sa.BINARY(length=32), nullable=False),
    sa.Column('archive_id', sa.Integer(), nullable=False),
    sa.Column('insert_date', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('hash', 'archive_id', 'field', 'insert_date'),
    if_not_exists=True
    )
    _create_index_if_missing(conn, 'idx_archive_id', 'archive_index', ['archive_id'])
    _create_index_if_missing(conn, 'idx_field_hash', 'archive_index', ['field', 'hash'])
    op.create_table('archive_server',
    sa.Column('server_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hostname', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('server_id'),
    sa.UniqueConstraint('hostname', name='idx_hostname'),
    if_not_exists=True
    )
    op.create_table('email_history',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('insert_date', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('message_id', sa.Text(), nullable=False),
    sa.Column('message_id_hash', sa.BINARY(length=32), nullable=False),
    sa.Column('recipient', sa.Text(), nullable=False),
    sa.Column('recipient_hash', sa.BINARY(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id', 'insert_date'),
    sa.UniqueConstraint('message_id_hash', 'recipient_hash', 'insert_date', name='idx_eh_message_id_recipient'),
    if_not_exists=True
    )
    _create_index_if_missing(conn, 'idx_eh_insert_date', 'email_history', ['insert_date'])
    _create_index_if_missing(conn, 'idx_eh_message_id', 'email_history', ['message_id_hash'])
    _create_index_if_missing(conn, 'idx_eh_recipient', 'email_history', ['recipient_hash'])
    # ### end Alembic commands ###

    # --- establish initial partitioning ---------------------------------------
    # only on a table that has no partitions yet, so an already-partitioned
    # production table (weekly pYYYYwWW partitions + p_catchall) is untouched.
    # This matches ensure_table_partitioned() in
    # bin/manage-email-archive-partitions.sh; the weekly split/prune of
    # p_catchall stays owned by that script.
    for table in PARTITIONED_TABLES:
        if _partition_count(conn, table) == 0:
            op.execute(
                f"ALTER TABLE `{table}` PARTITION BY RANGE COLUMNS(insert_date) "
                "(PARTITION p_catchall VALUES LESS THAN (MAXVALUE))"
            )


def downgrade() -> None:
    # Intentionally irreversible. This is the initial-schema revision for the
    # email-archive database, so there is nothing to revert to. Running it would DROP
    # every table -- and on a database that upgrade() merely stamped (a
    # pre-alembic deployment) that destroys live production data rather than
    # reverting a change. Refuse to run instead of risking that.
    raise RuntimeError(
        "refusing to downgrade the initial email-archive schema: it would drop the "
        "entire email-archive database. If you really need to tear it down, do it "
        "manually and restore from backup."
    )
